library(neuprintr)
box::use(mancfuns/han)
box::use(mancfuns/manc/annotation)
library(gplots)
library(viridis)
library(malevnc)
library(igraph)
library(svglite)

ds_syn_thres = 3
mtahn = c(42819,11003)
msahn = c(12536, 13926)
ahns = list(MtAHN=mtahn, MsAHN=msahn)
type_1 = c(23510,22289,22472,101206,21307,23628,20774,18519,157981,20590,18048,14502,16970,19315,18370,14625,32328,15337,23485,18657,18517,20537,15586,36805,22521,21381,23462,24945,153911,23191,23638,13060,22220,24442,155196,20586,16638,15788,17055,15113,101682,17945)
#file generated by manc_ahn_direct_ds.R
mtahn_ds = read.csv('syn_count_by_group_outliers.csv') #actually both mt and ms

for (i in names(ahns)) {
	mtahn_and_ds = neuprint_list2df(neuprint_fetch_custom(cypher=paste0("MATCH (a:Neuron) WHERE a.group IN [", paste(mtahn_ds$group[mtahn_ds$ahn == i], collapse = ','), "] RETURN a.bodyId AS bodyid"), timeout=2000))
	mtahn_and_ds = mtahn_and_ds$bodyid[mtahn_and_ds$bodyid %in% neuprint_connection_table(ahns[[i]], prepost = "POST", threshold = ds_syn_thres)$partner]
	all_bodyids = mtahn_and_ds 

	clio_manc_data = manc_neuprint_meta(mtahn_and_ds)
	clio_manc_data$abbrv = han$class2abbrv(clio_manc_data$class)
	#check if type is unique to group, if not append group to type for node labels
	
	all_neurons = neuprintr::neuprint_list2df(neuprintr::neuprint_fetch_custom(cypher=paste0("MATCH (a:Neuron) WHERE a.class IN ['", paste0(names(han$manc_neuron_type_lookup)[!(han$manc_neuron_type_lookup %in% c('ND','Glia'))], collapse="','"), "'] RETURN a.bodyId AS bodyid, a.class AS class, a.group AS group, a.type AS type"), timeout=2000))
	clio_manc_data$temp_label = apply(clio_manc_data[c("type","group")], MARGIN=1, FUN = function(x) { #if(all(clio_manc_data$group[clio_manc_data$type %in% x["type"]] %in% all_neurons$group[all_neurons$type %in% x["type"]]) 
		if(length(unique(all_neurons$group[all_neurons$type %in% x["type"]]))==1)
		return(x["type"]) else return(paste(x["type"], x["group"]))})
	#clio_manc_data$temp_label = paste(clio_manc_data$abbrv, clio_manc_data$group)
	#clio_manc_data$temp_label[clio_manc_data$bodyid %in% c(42819,11003)] = "MtAHN"
	# clio_manc_data$temp_label[clio_manc_data$abbrv == "MN"] = paste(clio_manc_data$type[clio_manc_data$abbrv == "MN"], clio_manc_data$group[clio_manc_data$abbrv == "MN"])
	# clio_manc_data$temp_label[clio_manc_data$abbrv == "DN"] = ifelse(is.na(annotation$type4id(clio_manc_data$bodyid[clio_manc_data$abbrv == "DN"])),
		# paste("DN", clio_manc_data$group[clio_manc_data$abbrv == "DN"]),
		# paste(annotation$type4id(clio_manc_data$bodyid[clio_manc_data$abbrv == "DN"]), clio_manc_data$group[clio_manc_data$abbrv == "DN"]))
	clio_manc_data$temp_label = ifelse(clio_manc_data$bodyid %in% type_1, paste("Tect IN", clio_manc_data$group), clio_manc_data$temp_label)
	clio_manc_data$cell_count = sapply(clio_manc_data$temp_label, FUN = function(x) sum(clio_manc_data$temp_label == x))
	clio_manc_data$minimal_label = ifelse(clio_manc_data$abbrv %in% c("DN","MN"), clio_manc_data$temp_label, clio_manc_data$group)
	clio_manc_data$temp_label = paste0(clio_manc_data$temp_label, "(", clio_manc_data$cell_count, ")")


	names(mtahn_and_ds) = clio_manc_data$temp_label[match(mtahn_and_ds, clio_manc_data$bodyid)]

	adj = neuprint_get_adjacency_matrix(mtahn_and_ds, timeout = 2000)
	adj = apply(adj, 2, function(x) tapply(x, names(mtahn_and_ds)[match(rownames(adj), mtahn_and_ds)], sum, na.rm = TRUE))
	adj = t(apply(t(adj), 2, function(x) tapply(x, names(mtahn_and_ds)[match(colnames(adj), mtahn_and_ds)], sum, na.rm = TRUE)))
	#adj_order = order(adj["MtAHN(2)",], decreasing = TRUE)
	#adj_order = c(adj_order[length(adj_order)], adj_order[1:(length(adj_order)-1)])
	#adj = adj[adj_order, adj_order]
	#adj = adj[unique(clio_manc_data$temp_label), unique(clio_manc_data$temp_label)]

	d=dist(adj,method="euclidean")
	Rowv = rowMeans(adj, na.rm = T)
	fit = hclust(d, method="ward.D2")
	fit = reorder(as.dendrogram(fit),Rowv)
	cluster = adj[labels(fit),labels(fit)]
	heatmap.2(cluster, col = viridis(100),scale="none",density.info='none',xlab="Output",ylab="Input",
		dendrogram='none',Rowv=FALSE,Colv=FALSE,trace='none',sepcolor='black', cexRow = 0.22 + 1/log10(ncol(cluster)), cexCol = 0.22 + 1/log10(ncol(cluster)), margins = c(10, 10))
	dev.off()

	#svglite(filename = paste0("mtahn_adj_matrix_to_partners_by_boxplot_outlier_log10(x+1)_transform_", Sys.Date(),".svg"), height=ceiling((18*nrow(adj)+200)/72), width=ceiling((18*ncol(adj)+200)/72))
	# png(file=paste0(i, "_adj_matrix_to_partners_by_boxplot_outlier_log10(x+1)_transform_", Sys.Date(),".png"), height=18*nrow(adj)+200, width=18*ncol(adj)+200)
	# heatmap.2(log10(adj+1), col = viridis(100),scale="none",density.info='none',xlab="Output",ylab="Input",
		# dendrogram='none',Rowv=FALSE,Colv=FALSE,trace='none',sepcolor='black', cexRow = 0.22 + 1/log10(ncol(adj)), cexCol = 0.22 + 1/log10(ncol(adj)), margins = c(10, 10))
	# dev.off()
	# write.csv(adj, paste0(i, "_adj_matrix_to_partners_by_boxplot_outlier_log10(x+1)_transform_", Sys.Date(),".csv"))

	# svglite(filename = paste0(i, "_adj_matrix_to_partners_by_boxplot_outlier_log10(x+1)_transform_", Sys.Date(),".svg"), height=ceiling((18*nrow(adj)+200)/72), width=ceiling((18*ncol(adj)+200)/72))
	# heatmap.2(log10(adj+1), col = viridis(100),scale="none",density.info='none',xlab="Output",ylab="Input",
		# dendrogram='none',Rowv=FALSE,Colv=FALSE,trace='none',sepcolor='black', cexRow = 0.22 + 1/log10(ncol(adj)), cexCol = 0.22 + 1/log10(ncol(adj)), margins = c(10, 10))
	# dev.off()

	svglite(filename = paste0(i, "_adj_matrix_to_partners_by_boxplot_outlier_no_transform_", Sys.Date(),".svg"), height=ceiling((18*nrow(adj)+200)/72), width=ceiling((18*ncol(adj)+200)/72))
	heatmap.2(adj, col = viridis(100),scale="none",density.info='none',xlab="Output",ylab="Input",
		dendrogram='none',Rowv=FALSE,Colv=FALSE,trace='none',sepcolor='black', cexRow = 0.22 + 1/log10(ncol(adj)), cexCol = 0.22 + 1/log10(ncol(adj)), margins = c(10, 10))
	dev.off()

	#han$graph_from_bodyid(mtahn_and_ds, threshold = 100L, by_group = TRUE, save_name = "mtahn_ds_manc_graph")

	#export in pajek format
	adj = adj[order(clio_manc_data$abbrv[match(rownames(adj),clio_manc_data$temp_label)]),
		order(clio_manc_data$abbrv[match(rownames(adj),clio_manc_data$temp_label)])]
	mtahn_graph = graph_from_adjacency_matrix(adj, mode = "directed", weighted = TRUE, diag = FALSE)
	mtahn_graph = delete_edges(mtahn_graph, edges = which(E(mtahn_graph)$weight < 100))
	graph_lut = c(MsAHN = "#ffe099", MtAHN = "#ffff64", AN = "#9632fa", DN = "#5ce7e1", IN = "#ff6666", MN = "#1910c7", SN = "#db58d7", ASN = "#ffc9b4", EN = "#80c8ff", AEN = "#b9b4ff", ND = "#aaaaaa")
	V(mtahn_graph)$color = graph_lut[match(clio_manc_data$abbrv[match(V(mtahn_graph)$name,clio_manc_data$temp_label)] , names(graph_lut))]
	V(mtahn_graph)$label = sapply(igraph::V(mtahn_graph)$name, FUN = function(x) paste0(stringi::stri_wrap(x, width = 12), collapse = "\n"))
	V(mtahn_graph)$cell_count = clio_manc_data$cell_count[match(V(mtahn_graph)$name, clio_manc_data$temp_label)]
	V(mtahn_graph)$minimal_label = clio_manc_data$minimal_label[match(V(mtahn_graph)$name, clio_manc_data$temp_label)]
	V(mtahn_graph)$enum = 1:length(V(mtahn_graph))
	#write_graph(mtahn_graph, file = "mtahn_ds_pajek.net", format = "pajek")
	#write.table(data.frame(index = 1:length(V(mtahn_graph)), name = V(mtahn_graph)$name, ic = "ic", color = V(mtahn_graph)$color), file = "mtahn_ds_pajek_names.txt", sep = " ", row.names = FALSE)

	#edge curve determination function. If nodes far, apply gentle curve of 0.2. If near (within 8 positions in ring), apply extreme curve of 1.
	ring_graph_edge_curve <-function (graph)
	{
		V(graph)$name = 1:length(V(graph))
		n_nodes = length(V(graph))
		graph = as_edgelist(graph)
		difference = as.integer(graph[,2]) - as.integer(graph[,1])
		difference = ifelse(difference > n_nodes/2, 
			-n_nodes + difference, 
			ifelse(difference < -n_nodes/2,
				n_nodes + difference,
				difference))
		curvature = (n_nodes/2 - abs(difference))*sign(difference)/(n_nodes/4)
		# curvature = ifelse(difference > 8, 0.2, ifelse(
			# difference < -8, -0.2, ifelse(
				# difference > 0, 1, ifelse(
					# difference < 0, -1, NA))))
		return(curvature)
	}

	layout_circle = layout_in_circle(mtahn_graph)
	#add more node positions that are mock nodes for line thickness legend
	layout_legend = matrix(0, nrow = 10, ncol = 2)
	layout_legend[,2] = c(0.8, 0.8, 0.85, 0.85, 0.9, 0.9, 0.95, 0.95, 1,1)
	layout_legend[,1] = c(0.8, 1)
	layout_circle = rbind(layout_circle, layout_legend)
	mtahn_graph_w_legend = add_vertices(mtahn_graph, nv = 10, attr = list(name=c(paste('legend', 1:10))))
	mtahn_graph_w_legend = add_edges(mtahn_graph_w_legend, edges = length(V(mtahn_graph))+1:10, attr = list(weight = c(10000, 5000, 1000, 500, 100)))
	E(mtahn_graph_w_legend)$curvature = c(ring_graph_edge_curve(mtahn_graph),rep(0,5))

	svglite(paste0(i, "_ds_graph_syn_thres_100_", Sys.Date(),".svg"), width = 10, height = 10)
	print(plot.igraph(mtahn_graph, edge.arrow.size = 0.8, vertex.size = 10,
		edge.arrow.width = 1, edge.label = NA, edge.width = E(mtahn_graph)$weight/500, vertex.color = V(mtahn_graph)$color, edge.curved = ring_graph_edge_curve(mtahn_graph),
		margin = c(0,0,0,0), layout = layout_in_circle, vertex.label.family = "sans", vertex.label.cex = 0.65, edge.label.family = "sans", edge.label.cex = 0.6))
	dev.off()

	svglite(paste0(i, "_ds_graph_syn_thres_100_w_legend", Sys.Date(),".svg"), width = 10, height = 10)
	print(plot.igraph(mtahn_graph_w_legend, edge.arrow.size = 0.8, vertex.size = c(rep(10, length(V(mtahn_graph))), rep(0,10)),
		edge.arrow.width = 1, curved = TRUE, edge.label = NA, edge.width = E(mtahn_graph_w_legend)$weight/500, vertex.color = V(mtahn_graph_w_legend)$color, edge.curved = c(ring_graph_edge_curve(mtahn_graph),rep(0,5)),
		margin = c(0,0,0,0), layout = layout_circle, vertex.label.family = "sans", vertex.label.cex = 0.65, edge.label.family = "sans", edge.label.cex = 0.6))
	dev.off()

	RCy3::createNetworkFromIgraph(mtahn_graph_w_legend, paste0(i, "_ds"))

}
